In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing

**2 a) To convert a list of numeric values into a 1 dimensional NumPY array.**

In [2]:
myList = [87,45,74,98]

myArray = np.array(myList)

print(myArray)

[87 45 74 98]


**2 b) To create a 3*3 matrix with values ranging from 2 to 10.**

In [3]:
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**2 c) To append value at the end of array.**

In [4]:
my_array = np.array([10,20,30,40])
valueAppend = 50

my_array = np.append(my_array, valueAppend)

print(my_array)


[10 20 30 40 50]


**2 d) To create another shape from an array without changing its data(3*2 to 2*3)**

In [5]:
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

reshaped_array = original_array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]
